image:
  file: .gitpod.Dockerfile
tasks:
  - name: Setup Environment
    init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
vscode:
  extensions:
    - ms-python.debugpy
    - PKief.material-icon-theme
    - charliermarsh.ruff
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - batisteo.vscode-django
    - esbenp.prettier-vscode
    - christian-kohler.path-intellisense
    - yzhang.markdown-all-in-one
    - GitHub.github-vscode-theme
