image:
  file: .gitpod.Dockerfile
tasks:
  - name: Setup Environment
    init: |
      clear
      . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: |
      python ${GITPOD_REPO_ROOT}/.vscode/display_repo_info.py
vscode:
  extensions:
    - ms-python.debugpy
    - PKief.material-icon-theme
    - charliermarsh.ruff
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - esbenp.prettier-vscode
    - christian-kohler.path-intellisense
    - yzhang.markdown-all-in-one
    - GitHub.github-vscode-theme
    - matt-rudge.auto-open-preview-panel
    - formulahendry.auto-rename-tag
    - formulahendry.auto-close-tag
    - formulahendry.code-runner
    - donjayamanne.python-extension-pack
