image:
  file: .gitpod.Dockerfile
tasks:
  - name: Setup Environment
    init: |
      clear
      . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: |
      python ${GITPOD_REPO_ROOT}/.vscode/display_repo_info.py
